### ISSUE TITLE
Unable to run jar file

### ISSUE THREAD

**Issue by ivancze** [AY2021S2-CS2113-T10-3/tp#27]
I am unable to run your released jar file as shown in the screenshot below.

![image](https://user-images.githubusercontent.com/70261399/113466666-243a9880-9470-11eb-8ea2-1b9b3b32260c.png)

I think it might be because you did not build your jar correctly. Using intelliJ's "Build artifact" feature does not work. You probably need to build it using gradle Shadowjar task. You can refer [here](https://se-education.org/guides/tutorials/gradle.html), under Creating a Jar file, if you need to. Thanks!

@okkhoy
@xhxh96

**Comment by okkhoy** [comment]
@Tyuanyuan @Zufiqqar @L-Irvin  @violinyap  @boonjuey

For your immediate action.

please release a new jar file asap after fixing this error. the testers will then download the latest one

**Comment by ivancze** [comment]
Sorry for the overlook! I was following the module website instructions which told us to run the jar using "java -jar". Managed to run app after running the command as mentioned in UG:
![image](https://user-images.githubusercontent.com/70261399/113471143-f152cd80-948c-11eb-9ab4-87df87ac4955.png)

@okkhoy 
@xhxh96

**Comment by okkhoy** [comment]
This is still a bug. The java -jar is standard way to run jar files.
Specifying class path should not be necessary. The JAR should be packaged such that the main class file should be automatically picked up when the Jar file is run.

If you use shadowjar appropriately, things will be taken care of automatically.

**Comment by ivancze** [comment]
Shall I reopen the issue prof @okkhoy ?
